export const en = {
  collapse: "Collapse",
  expand: "Expand",

  fieldDescriptionPlaceholder: "Describe what this field is used for",
  fieldDelete: "Delete field",
  fieldDescription: "Description",
  fieldDescriptionTooltip: "Add context about what this field represents",
  fieldNameLabel: "Field name",
  fieldNamePlaceholder: "e.g. firstName, age, isActive",
  fieldNameTooltip: "Use camelCase for readability (e.g. firstName)",
  fieldRequiredLabel: "Required field",
  fieldType: "Field type",
  fieldTypeExample: "Example:",
  fieldTypeTooltipString: "string: text",
  fieldTypeTooltipNumber: "number: number",
  fieldTypeTooltipBoolean: "boolean: true/false",
  fieldTypeTooltipObject: "object: nested JSON object",
  fieldTypeTooltipArray: "array: list",
  fieldAddNewButton: "Add field",
  fieldAddNewBadge: "Schema builder",
  fieldAddNewCancel: "Cancel",
  fieldAddNewConfirm: "Add field",
  fieldAddNewDescription: "Create a new field for your JSON schema",
  fieldAddNewLabel: "Add new field",

  fieldTypeTextLabel: "String",
  fieldTypeTextDescription: "For text values such as names, descriptions, etc.",
  fieldTypeNumberLabel: "Number",
  fieldTypeNumberDescription: "For decimals or integers",
  fieldTypeBooleanLabel: "Boolean",
  fieldTypeBooleanDescription: "For true/false values",
  fieldTypeObjectLabel: "Object",
  fieldTypeObjectDescription: "For grouping related fields",
  fieldTypeArrayLabel: "Array",
  fieldTypeArrayDescription: "For collection items",

  propertyDescriptionPlaceholder: "Add description...",
  propertyDescriptionButton: "Add description...",
  propertyRequired: "Required",
  propertyOptional: "Optional",
  propertyDelete: "Delete field",

  schemaEditorTitle: "JSON Schema Editor",
  schemaEditorToggleFullscreen: "Toggle fullscreen",
  schemaEditorShowSource: "Show JSON source",
  schemaEditorHideSource: "Hide JSON source",
  schemaEditorEditModeVisual: "Visual",
  schemaEditorEditModeJson: "JSON",
  schemaEditorLoading: "Loading editor...",

  arrayNoConstraint: "No constraint",
  arrayMinimumLabel: "Minimum items",
  arrayMinimumPlaceholder: "No minimum items constraint",
  arrayMaximumLabel: "Maximum items",
  arrayMaximumPlaceholder: "No maximum items constraint",
  arrayForceUniqueItemsLabel: "Force unique items (no duplicates allowed)",
  arrayItemTypeLabel: "Item type",
  arrayValidationErrorMinMax:
    '"Minimum items" cannot be greater than "Maximum items"',
  arrayValidationErrorContainsMinMax:
    '"Minimum contains" cannot be greater than "Maximum contains"',

  booleanNoConstraint: "No constraint",
  booleanAllowedValuesLabel: "Allowed values",
  booleanAllowFalseLabel: "Allow value false",
  booleanAllowTrueLabel: "Allow value true",
  booleanNeitherWarning: "Warning: You must allow at least one value.",

  numberNoConstraint: "No constraint",
  numberMinimumLabel: "Minimum (inclusive)",
  numberMinimumPlaceholder: "No minimum (inclusive) constraint",
  numberMaximumLabel: "Maximum (inclusive)",
  numberMaximumPlaceholder: "No maximum (inclusive) constraint",
  numberExclusiveMinimumLabel: "Minimum (exclusive)",
  numberExclusiveMinimumPlaceholder: "No minimum (exclusive) constraint",
  numberExclusiveMaximumLabel: "Maximum (exclusive)",
  numberExclusiveMaximumPlaceholder: "No maximum (exclusive) constraint",
  numberMultipleOfLabel: "Multiple of",
  numberMultipleOfPlaceholder: "Any number",
  numberAllowedValuesEnumLabel: "Allowed values (enum)",
  numberAllowedValuesEnumNone: "No restricted values currently",
  numberAllowedValuesEnumAddLabel: "Add",
  numberAllowedValuesEnumAddPlaceholder: "Add an allowed value...",
  numberValidationErrorMinMax: "Minimum and maximum must be consistent.",
  numberValidationErrorBothExclusiveAndInclusiveMin:
    '"Minimum (inclusive)" and "Minimum (exclusive)" cannot both be set.',
  numberValidationErrorBothExclusiveAndInclusiveMax:
    '"Maximum (inclusive)" and "Maximum (exclusive)" cannot both be set.',
  numberValidationErrorEnumOutOfRange:
    "Enum values must be within the defined range.",

  objectPropertiesNone: "No properties defined",
  objectValidationErrorMinMax:
    '"Minimum properties" cannot be greater than "Maximum properties".',

  additionalPropertiesAllow: "Allow additional properties",
  additionalPropertiesForbid: "Forbid additional properties",
  additionalPropertiesTooltip:
    "Controls whether properties not defined in 'properties' or 'patternProperties' are allowed",

  stringNoConstraint: "No constraint",
  stringMinimumLengthLabel: "Minimum length",
  stringMinimumLengthPlaceholder: "No minimum length",
  stringMaximumLengthLabel: "Maximum length",
  stringMaximumLengthPlaceholder: "No maximum length",
  stringPatternLabel: "Pattern (regex)",
  stringPatternPlaceholder: "^[a-zA-Z]+$",
  stringFormatLabel: "Format",
  stringFormatNone: "None",
  stringFormatDateTime: "Date time",
  stringFormatDate: "Date",
  stringFormatTime: "Time",
  stringFormatEmail: "Email",
  stringFormatUri: "URI",
  stringFormatUuid: "UUID",
  stringFormatHostname: "Hostname",
  stringFormatIpv4: "IPv4 address",
  stringFormatIpv6: "IPv6 address",
  stringAllowedValuesEnumLabel: "Allowed values (enum)",
  stringAllowedValuesEnumNone: "No restricted values currently",
  stringAllowedValuesEnumAddPlaceholder: "Add an allowed value...",
  stringAllowedValuesEnumAddLabel: "Add",
  stringFormatSelectPlaceholder: "Select format",
  stringValidationErrorLengthRange:
    '"Minimum length" cannot be greater than "Maximum length"',

  schemaTypeArray: "Array",
  schemaTypeBoolean: "Boolean",
  schemaTypeNumber: "Number",
  schemaTypeObject: "Object",
  schemaTypeString: "String",
  schemaTypeNull: "Null",

  inferrerTitle: "Infer JSON Schema",
  inferrerDescription:
    "Paste your JSON document to generate the corresponding schema.",
  inferrerCancel: "Cancel",
  inferrerGenerate: "Generate schema",
  inferrerErrorInvalidJson: "Invalid JSON format. Please check your input.",

  validatorTitle: "Validate JSON",
  validatorDescription:
    "Paste your JSON document to validate against the current schema. Validation runs automatically as you type.",
  validatorCurrentSchema: "Current schema:",
  validatorContent: "Your JSON:",
  validatorValid: "JSON conforms to the schema!",
  validatorErrorInvalidSyntax: "Invalid JSON syntax",
  validatorErrorSchemaValidation: "Schema validation error",
  validatorErrorCount: "{count} validation error(s) detected",
  validatorErrorPathRoot: "Root",
  validatorErrorLocationLineAndColumn: "Line {line}, column {column}",
  validatorErrorLocationLineOnly: "Line {line}",

  visualizerDownloadTitle: "Download schema",
  visualizerDownloadFileName: "schema.json",
  visualizerSource: "JSON Schema source",

  visualEditorNoFieldsHint1: "No fields defined",
  visualEditorNoFieldsHint2: "Add your first field to get started",

  typeValidationErrorNegativeLength: "Length values cannot be negative.",
  typeValidationErrorIntValue: "Value must be an integer.",
  typeValidationErrorPositive: "Value must be positive.",

  demoSubtitle: "Visual JSON Schema editor based on Vue 3 + Element Plus",
  demoBasicTitle: "Basic usage",
  demoBasicDesc:
    "Visual editing on the left, live JSON source on the right, with a draggable splitter and fullscreen.",
  demoVisualOnlyTitle: "Visual-only mode",
  demoVisualOnlyDesc:
    'Set show-json-editor="false" to show only the visual panel.',
  demoReadonlyTitle: "Read-only mode",
  demoReadonlyDesc: "Set read-only to disable all editing operations.",
  demoNoFullscreenTitle: "Hide fullscreen button",
  demoNoFullscreenDesc: 'Set show-fullscreen="false".',
  demoInferTitle: "Infer schema from JSON",
  demoInferDesc:
    "Paste JSON data and generate the corresponding JSON Schema in one click.",
  demoValidateTitle: "JSON data validation",
  demoValidateDesc:
    "Powered by Ajv, validates JSON data against the current schema.",
  demoDialogMode: "Dialog mode",
  demoInlineMode: "Inline mode",
  demoCollapseInline: "Collapse inline",
  demoOpenValidator: "Open validator dialog",
  demoToggleSourceTitle: "Toggle source panel",
  demoToggleSourceDesc:
    "Use the toggle button next to the fullscreen button to show or hide the JSON source panel at any time.",
  demoPropSourceTitle: "Control source panel via props",
  demoPropSourceDesc:
    "Set source-visible for the initial state, supports v-model:source-visible two-way binding.",
  demoShowSource: "Show source",
  demoHideSource: "Hide source",
};
